import hmac
import hashlib
import os
import json
import logging
import logging.config
import httpx
from google import genai
from fastapi import FastAPI, Request, HTTPException, Header, Depends
from typing import Optional, Dict, Any
from dotenv import load_dotenv
from github import Github, Auth
import anyio
from tenacity import retry, stop_after_attempt, wait_exponential, retry_if_exception_type

load_dotenv()

# Configure Logging
LOGGING_CONFIG = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
        },
    },
    'handlers': {
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
    },
    'loggers': {
        '': {  # root logger
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': True
        },
        'httpx': {
            'level': 'WARNING',
            'propagate': False,
            'handlers': ['console'],
        },
    }
}
logging.config.dictConfig(LOGGING_CONFIG)
logger = logging.getLogger(__name__)

# Startup Checks
WEBHOOK_SECRET = os.getenv("WEBHOOK_SECRET")
if not WEBHOOK_SECRET:
    logger.critical("WEBHOOK_SECRET is not set in environment variables. Application cannot start safely.")
    raise RuntimeError("WEBHOOK_SECRET is required.")

app = FastAPI()

# Configuration Constants
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN") # Legacy/Fallback
GITHUB_APP_ID = os.getenv("GITHUB_APP_ID")
GITHUB_PRIVATE_KEY = os.getenv("GITHUB_PRIVATE_KEY")

CONFIG_FILE = "config.json"
app_config = {
    "active_model": os.getenv("AI_MODEL_NAME", "gemini-2.5-flash")
}

def load_app_config():
    """Loads application configuration from a local JSON file."""
    if os.path.exists(CONFIG_FILE):
        try:
            with open(CONFIG_FILE, "r") as f:
                config = json.load(f)
                app_config["active_model"] = config.get("active_model", app_config["active_model"])
                logger.info(f"Loaded active model from {CONFIG_FILE}: {app_config['active_model']}")
        except Exception as e:
            logger.error(f"Failed to load {CONFIG_FILE}: {str(e)}")

def save_app_config(model_name: str):
    """Saves application configuration to a local JSON file."""
    try:
        with open(CONFIG_FILE, "w") as f:
            json.dump({"active_model": model_name}, f)
            logger.info(f"Saved active model to {CONFIG_FILE}: {model_name}")
    except Exception as e:
        logger.error(f"Failed to save {CONFIG_FILE}: {str(e)}")

@app.on_event("startup")
async def startup_event():
    load_app_config()

APP_NAME = "Code Review Automator"
AI_REVIEW_HEADER = "## Automated Code Review"
AI_REVIEW_DISCLAIMER = "> **Note:** This review was generated by an AI model. Please verify these suggestions before committing any changes."
MAX_TOKENS = 100000
GITHUB_COMMENT_LIMIT = 65000 # Safety margin below 65536

# Dependency Providers
def get_github_client(installation_id: Optional[int] = None) -> Github:
    if GITHUB_APP_ID and GITHUB_PRIVATE_KEY:
        try:
            # Replace escaped newlines if they are passed in env var
            private_key = GITHUB_PRIVATE_KEY.replace('\\n', '\n')
            if installation_id:
                auth = Auth.AppInstallationAuth(GITHUB_APP_ID, private_key, installation_id)
            else:
                auth = Auth.AppAuth(GITHUB_APP_ID, private_key)
            return Github(auth=auth)
        except Exception as e:
            logger.error(f"Failed to initialize GitHub App auth: {str(e)}")
            raise HTTPException(status_code=500, detail="GitHub App authentication failed.")
    
    if GITHUB_TOKEN:
        logger.warning("Using GITHUB_TOKEN (PAT) is deprecated. Please switch to GitHub App.")
        auth = Auth.Token(GITHUB_TOKEN)
        return Github(auth=auth)
    
    logger.error("No GitHub authentication configured (GITHUB_APP_ID/PRIVATE_KEY or GITHUB_TOKEN).")
    raise HTTPException(status_code=500, detail="GitHub client not configured.")

def get_gemini_client() -> genai.Client:
    if not GEMINI_API_KEY:
        logger.error("GEMINI_API_KEY not found in environment variables.")
        raise HTTPException(status_code=500, detail="Gemini client not configured.")
    return genai.Client(api_key=GEMINI_API_KEY)

async def verify_signature(signature: str, raw_payload: bytes):
    """
    Verifies that the signature in the header matches the payload's HMAC.
    """
    if not WEBHOOK_SECRET:
        return

    if not signature:
        raise HTTPException(status_code=401, detail="X-Hub-Signature-256 header is missing")

    try:
        sha_name, signature_hash = signature.split('=')
        if sha_name != 'sha256':
            raise HTTPException(status_code=401, detail="Unsupported signature algorithm")
    except ValueError:
        raise HTTPException(status_code=401, detail="Invalid signature format")

    mac = hmac.new(WEBHOOK_SECRET.encode(), msg=raw_payload, digestmod=hashlib.sha256)
    expected_signature = mac.hexdigest()

    if not hmac.compare_digest(expected_signature, signature_hash):
        raise HTTPException(status_code=401, detail="Invalid signature")

@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=2, max=10),
    retry=retry_if_exception_type((httpx.HTTPError, Exception))
)
def download_diff(github_token: str, repo_full_name: str, pr_number: int) -> str:
    """
    Downloads the raw diff content using the GitHub API with a specialized Accept header.
    """
    if not github_token:
        logger.error("github_token is required for download_diff.")
        return ""

    try:
        url = f"https://api.github.com/repos/{repo_full_name}/pulls/{pr_number}"

        headers = {
            "Authorization": f"token {github_token}",
            "Accept": "application/vnd.github.v3.diff"
        }

        with httpx.Client(timeout=30.0) as client:
            response = client.get(url, headers=headers)

            if response.status_code == 200:
                return response.text
            else:
                logger.warning(f"Failed to fetch diff via API: {response.status_code}")
                try:
                    error_details = response.json()
                    logger.error(f"GitHub API error details: {error_details}")
                except (json.JSONDecodeError, httpx.DecodingError):
                    logger.error(f"GitHub API error details (raw text): {response.text}")
                return ""

    except httpx.HTTPError as e:
        logger.error(f"HTTP error fetching diff for {repo_full_name} PR #{pr_number}: {str(e)}")
        raise e # Let tenacity retry
    except Exception as e:
        logger.exception(f"Error fetching diff for {repo_full_name} PR #{pr_number}: {str(e)}")
        raise e

@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=2, max=10)
)
def post_github_comment(github_client: Github, repo_full_name: str, pr_number: int, comment_body: str, model_name: str):
    """
    Posts a comment to the specified GitHub Pull Request using PyGithub.
    """
    if not github_client:
        logger.error("Error: PyGithub client not provided to post_github_comment.")
        return

    try:
        repo = github_client.get_repo(repo_full_name)
        pr = repo.get_pull(pr_number)
        
        # Formatting the comment with a header
        header = f"{AI_REVIEW_HEADER}\n\n{AI_REVIEW_DISCLAIMER}\n\n"
        footer = f"\n\n---\n<sub> Powered by {model_name} • {APP_NAME}</sub>"
        
        # Truncation logic
        max_body_length = GITHUB_COMMENT_LIMIT - len(header) - len(footer) - 100 # buffer
        if len(comment_body) > max_body_length:
            logger.warning(f"Comment body too long ({len(comment_body)} characters), truncating.")
            truncation_msg = "\n\n**[Review truncated due to GitHub character limit]**"
            comment_body = comment_body[:max_body_length - len(truncation_msg)] + truncation_msg

        formatted_comment = f"{header}{comment_body}{footer}"
        
        pr.create_issue_comment(formatted_comment)
        logger.info(f"Successfully posted comment to PR #{pr_number}")
    except Exception as e:
        logger.exception(f"Error posting comment to GitHub for PR #{pr_number}: {str(e)}")
        raise e

@retry(
    stop=stop_after_attempt(3),
    wait=wait_exponential(multiplier=1, min=2, max=10)
)
def get_gemini_review(gemini_client: genai.Client, diff_content: str, model_name: str) -> str:
    """
    Sends the diff content to Gemini for review with a custom prompt.
    """
    if not gemini_client:
        logger.error("Error: Gemini API client not provided to get_gemini_review.")
        return "ERROR: Gemini API client not configured."

    # Token Counting and Safety Check
    try:
        token_count_response = gemini_client.models.count_tokens(
            model=model_name,
            contents=diff_content
        )
        token_count = token_count_response.total_tokens
        logger.info(f"Diff token count: {token_count}")
        
        if token_count > MAX_TOKENS:
            logger.warning(f"Diff token count ({token_count}) exceeds MAX_TOKENS ({MAX_TOKENS}).")
            return f"ERROR: The code change is too large for automated review (contains approximately {token_count} tokens, limit is {MAX_TOKENS}). Please review manually."
    except Exception as e:
        logger.warning(f"Failed to count tokens: {str(e)}")
        # Proceed with caution if token counting fails

    prompt_instructions = """You are an expert Senior Staff Software Engineer and Security Auditor. Your task is to perform a brutal, production-readiness code review of the provided Git diff.

    Focus on:
    1. Bugs: Logic errors, off-by-one, null handling, race conditions, async/sync blocking.
    2. Security: Injection, auth bypass, data exposure, insecure defaults.
    3. Performance: N+1 queries, blocking I/O, memory leaks, token/payload limits.
    4. Maintainability: Monolithic design, magic strings, lack of logging, poor separation of concerns.
    5. Edge Cases: Large payloads, missing env vars, API rate limits.

    For every issue found, use this strict Markdown format:
    - **Severity:** [Critical/High/Medium/Low]
    - **Location:** [Line number or Function name in the diff, e.g., `main.py:123` or `function_name`]
    - **Issue:** [Concise description]
    - **Solution:** [Exact code fix or architectural change required]

    Be concise, direct, and actionable. Do not include pleasantries or conversational filler. Start immediately with the findings or state "No significant issues found." if applicable."""

    full_prompt = f"{prompt_instructions}\n\nCode Diff:\n{diff_content}"
    
    try:
        response = gemini_client.models.generate_content(
            model=model_name,
            contents=full_prompt
        )
        return response.text
    except Exception as e:
        logger.exception(f"Error calling Gemini API: {str(e)}")
        raise e

@app.post("/webhook")
async def webhook_handler(
    request: Request,
    x_hub_signature_256: Optional[str] = Header(None),
    gemini_client: genai.Client = Depends(get_gemini_client)
):
    """
    Handles incoming webhook requests from GitHub, downloads diffs, gets Gemini reviews, and posts comments.
    """
    # Read body once to avoid multiple consumption issues
    raw_payload = await request.body()
    
    await verify_signature(x_hub_signature_256, raw_payload)

    try:
        payload = json.loads(raw_payload)
    except json.JSONDecodeError:
        logger.error("Invalid JSON payload received.")
        raise HTTPException(status_code=400, detail="Invalid JSON payload")

    # Extract Installation ID for GitHub App auth
    installation_id = payload.get("installation", {}).get("id")
    action = payload.get("action")
    pull_request = payload.get("pull_request")
    
    if pull_request and action in ["opened", "synchronize", "reopened"]:
        repo_full_name = payload.get("repository", {}).get("full_name")
        pr_number = pull_request.get("number")

        logger.info(f"Processing PR #{pr_number} in {repo_full_name} for action: {action}")
        
        if repo_full_name and pr_number:
            try:
                # Initialize GitHub client for this specific installation
                github_client = get_github_client(installation_id)
                
                # Get a token for download_diff (httpx)
                github_token = GITHUB_TOKEN # Fallback to PAT
                if installation_id and GITHUB_APP_ID and GITHUB_PRIVATE_KEY:
                    try:
                        github_token = github_client.get_auth().token
                    except Exception as token_e:
                        logger.warning(f"Could not extract installation token: {str(token_e)}. Falling back to PAT if available.")

                if not github_token and not GITHUB_TOKEN:
                    logger.error("No valid GitHub token available for diff download.")
                    raise HTTPException(status_code=500, detail="GitHub authentication configuration missing.")

                # Use anyio to run blocking I/O in a thread pool
                logger.info(f"Fetching diff for PR #{pr_number}...")
                diff_content = await anyio.to_thread.run_sync(download_diff, github_token, repo_full_name, pr_number)
                
                if not diff_content:
                    logger.error(f"Failed to download diff for {repo_full_name} PR #{pr_number}. Aborting review.")
                    raise HTTPException(status_code=500, detail=f"Failed to retrieve PR diff from GitHub for {repo_full_name} #{pr_number}")

                active_model = app_config["active_model"]
                logger.info(f"Generating Gemini review using model: {active_model}...")
                review = await anyio.to_thread.run_sync(get_gemini_review, gemini_client, diff_content, active_model)
                
                if review.startswith("ERROR:") or review == "Gemini API client not configured.":
                    logger.error(f"Failed to generate Gemini review for {repo_full_name} PR #{pr_number}. Reason: {review}")
                    raise HTTPException(status_code=400 if "too large" in review else 500, detail=review)

                logger.info("Posting review to GitHub...")
                await anyio.to_thread.run_sync(post_github_comment, github_client, repo_full_name, pr_number, review, active_model)
                
                return {
                    "status": "success",
                    "message": "Webhook processed, review generated and posted to PR",
                    "review_preview": review[:100] + "..." if len(review) > 100 else review
                }
            except HTTPException as he:
                raise he
            except Exception as e:
                logger.exception(f"Unhandled error in webhook_handler during PR processing: {str(e)}")
                raise HTTPException(status_code=500, detail=f"Internal server error processing PR #{pr_number}: {str(e)}")

    return {"status": "success", "message": "Webhook received, no PR action taken"}

# Administration Endpoints
async def verify_admin_token(x_admin_token: Optional[str] = Header(None)):
    """Verifies the admin token for sensitive operations."""
    if not x_admin_token or x_admin_token != WEBHOOK_SECRET:
        raise HTTPException(status_code=403, detail="Unauthorized admin access")
    return x_admin_token

@app.get("/api/models")
async def list_models(
    gemini_client: genai.Client = Depends(get_gemini_client),
    _: str = Depends(verify_admin_token)
):
    """Lists Gemini models suitable for code review with a clean, formatted response."""
    try:
        models = []
        logger.info("Fetching and filtering models from Gemini API...")
        
        for model in gemini_client.models.list():
            # Use direct attribute access as some SDK versions strip attributes in model_dump()
            name = getattr(model, "name", "unknown")
            display_name = getattr(model, "display_name", name)
            
            # Try multiple attribute names for supported methods
            methods = (
                getattr(model, "supported_generation_methods", []) or 
                getattr(model, "supported_methods", [])
            )
            
            # Normalizing methods to lowercase for easier comparison
            methods_lower = [m.lower() for m in methods]
            is_text_model = any(m in ["generatecontent", "generate_content"] for m in methods_lower)
            
            # Fallback: if methods list is empty, include known text-capable families
            if not methods and any(family in name.lower() for family in ["gemini", "gemma"]):
                is_text_model = True

            if is_text_model:
                models.append({
                    "model_id": name,
                    "display_name": display_name,
                    "input_token_limit": getattr(model, "input_token_limit", "Unknown"),
                    "description": getattr(model, "description", "No description available")
                })
        
        # Sort by display name for better organization
        models.sort(key=lambda x: x["display_name"])
        
        logger.info(f"Returning {len(models)} filtered models.")
        return {
            "status": "success",
            "count": len(models),
            "models": models
        }
    except Exception as e:
        logger.exception(f"Error listing models: {str(e)}")
        raise HTTPException(status_code=500, detail=f"Failed to list models: {str(e)}")

@app.get("/api/models/active")
async def get_active_model(_: str = Depends(verify_admin_token)):
    """Returns the currently active model."""
    return {"active_model": app_config["active_model"]}

@app.post("/api/models/active")
async def set_active_model(
    payload: Dict[str, str],
    gemini_client: genai.Client = Depends(get_gemini_client),
    _: str = Depends(verify_admin_token)
):
    """Updates the active model used for reviews."""
    model_name = payload.get("model_name")
    if not model_name:
        raise HTTPException(status_code=400, detail="model_name is required")
    
    try:
        # Validate that the model exists
        gemini_client.models.get(model=model_name)
        
        # Update state and persist
        app_config["active_model"] = model_name
        save_app_config(model_name)
        
        return {"status": "success", "active_model": model_name}
    except Exception as e:
        logger.error(f"Failed to set active model to {model_name}: {str(e)}")
        raise HTTPException(status_code=400, detail=f"Invalid or inaccessible model: {model_name}")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
