from functools import lru_cache
from typing import Any, Optional

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    webhook_secret: str = Field(alias="WEBHOOK_SECRET")
    admin_api_key: Optional[str] = Field(default=None, alias="ADMIN_API_KEY")

    gemini_api_key: str = Field(alias="GEMINI_API_KEY")
    github_token: Optional[str] = Field(default=None, alias="GITHUB_TOKEN")
    github_app_id: Optional[str] = Field(default=None, alias="GITHUB_APP_ID")
    github_private_key: Optional[str] = Field(default=None, alias="GITHUB_PRIVATE_KEY")

    database_url: str = Field(default="sqlite:///./code_reviewer.db", alias="DATABASE_URL")
    ai_model_name: str = Field(default="gemini-2.5-flash", alias="AI_MODEL_NAME")

    app_name: str = Field(default="Code Review Automator", alias="APP_NAME")
    ai_review_header: str = Field(default="## Automated Code Review", alias="AI_REVIEW_HEADER")
    ai_review_disclaimer: str = Field(
        default=(
            "> **Note:** This review was generated by an AI model. "
            "Please verify these suggestions before committing any changes."
        ),
        alias="AI_REVIEW_DISCLAIMER",
    )
    ai_review_prompt: str = Field(
        default=(
            "You are an expert Senior Staff Software Engineer and Security Auditor. Review the provided Git diff and "
            "return ONLY valid JSON with no markdown fences and no extra text.\n\n"
            "Output schema:\n"
            "{\n"
            '  "summary": "High-level review summary",\n'
            '  "suggestions": [\n'
            "    {\n"
            '      "path": "relative/file/path.py",\n'
            '      "line": 42,\n'
            '      "message": "Issue + concrete fix",\n'
            '      "severity": "Critical|High|Medium|Low"\n'
            "    }\n"
            "  ]\n"
            "}\n\n"
            "Rules:\n"
            "1. Suggestions must only reference changed files in the diff.\n"
            "2. Line numbers must map to the right side (new code) of the diff.\n"
            "3. Keep each message concise, actionable, and implementation-focused.\n"
            "4. If there are no significant issues, return an empty suggestions array and a summary stating that.\n"
            "5. Focus on bugs, security, performance, maintainability, and edge cases.\n"
        ),
        alias="AI_REVIEW_PROMPT",
    )

    max_tokens: int = Field(default=100000, alias="MAX_TOKENS")
    github_comment_limit: int = Field(default=65000, alias="GITHUB_COMMENT_LIMIT")


@lru_cache
def get_settings() -> Settings:
    settings_cls: Any = Settings
    return settings_cls()
