from functools import lru_cache
from typing import Optional

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_file_encoding="utf-8", extra="ignore")

    webhook_secret: str = Field(alias="WEBHOOK_SECRET")
    admin_api_key: Optional[str] = Field(default=None, alias="ADMIN_API_KEY")

    gemini_api_key: str = Field(alias="GEMINI_API_KEY")
    github_token: Optional[str] = Field(default=None, alias="GITHUB_TOKEN")
    github_app_id: Optional[str] = Field(default=None, alias="GITHUB_APP_ID")
    github_private_key: Optional[str] = Field(default=None, alias="GITHUB_PRIVATE_KEY")

    database_url: str = Field(default="sqlite:///./code_reviewer.db", alias="DATABASE_URL")
    ai_model_name: str = Field(default="gemini-2.5-flash", alias="AI_MODEL_NAME")

    app_name: str = Field(default="Code Review Automator", alias="APP_NAME")
    ai_review_header: str = Field(default="## Automated Code Review", alias="AI_REVIEW_HEADER")
    ai_review_disclaimer: str = Field(
        default=(
            "> **Note:** This review was generated by an AI model. "
            "Please verify these suggestions before committing any changes."
        ),
        alias="AI_REVIEW_DISCLAIMER",
    )
    ai_review_prompt: str = Field(
        default=(
            "You are an expert Senior Staff Software Engineer and Security Auditor. Your task is to perform a brutal, "
            "production-readiness code review of the provided Git diff.\n\n"
            "Focus on:\n"
            "1. Bugs: Logic errors, off-by-one, null handling, race conditions, async/sync blocking.\n"
            "2. Security: Injection, auth bypass, data exposure, insecure defaults.\n"
            "3. Performance: N+1 queries, blocking I/O, memory leaks, token/payload limits.\n"
            "4. Maintainability: Monolithic design, magic strings, lack of logging, poor separation of concerns.\n"
            "5. Edge Cases: Large payloads, missing env vars, API rate limits.\n\n"
            "For every issue found, use this strict Markdown format:\n"
            "- **Severity:** [Critical/High/Medium/Low]\n"
            "- **Location:** [Line number or Function name in the diff, e.g., `main.py:123` or `function_name`]\n"
            "- **Issue:** [Concise description]\n"
            "- **Solution:** [Exact code fix or architectural change required]\n\n"
            "Be concise, direct, and actionable. Do not include pleasantries or conversational filler. "
            'Start immediately with the findings or state "No significant issues found." if applicable.'
        ),
        alias="AI_REVIEW_PROMPT",
    )

    max_tokens: int = Field(default=100000, alias="MAX_TOKENS")
    github_comment_limit: int = Field(default=65000, alias="GITHUB_COMMENT_LIMIT")


@lru_cache
def get_settings() -> Settings:
    return Settings()
